name: Instagram Follower Tracker

# Define when the workflow should run
on:
  schedule:
    # Run at 9 AM UTC every Monday
    - cron: '0 9 * * 1'
  # Allow manual triggering for testing purposes
  workflow_dispatch:

jobs:
  track-followers:
    runs-on: ubuntu-latest
    
    # Configure default shell behavior
    defaults:
      run:
        shell: bash

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only fetch the latest commit to save time

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'  # Enable pip caching for faster installations

      # Install required Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instaloader google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # Run the tracker script with all necessary environment variables
      - name: Run tracker
        env:
          # Instagram authentication
          IG_SESSION_COOKIE: ${{ secrets.IG_SESSION_COOKIE }}
          
          # Google Sheets API credentials and configuration
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          
          # Account lists to track
          ACCOUNTS_TO_TRACK: ${{ secrets.ACCOUNTS_TO_TRACK }}
          COMPETITOR_ACCOUNTS: ${{ secrets.COMPETITOR_ACCOUNTS }}
        run: python tracker.py

      # Error notification (optional but recommended)
      - name: Notify on failure
        if: failure()
        env:
          NOTIFICATION_URL: ${{ secrets.NOTIFICATION_URL }}
        run: |
          if [ ! -z "$NOTIFICATION_URL" ]; then
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"text\":\"❌ Instagram Follower Tracker failed to run\"}" \
              $NOTIFICATION_URL
          fi
