# .github/workflows/tracker.yml
name: Instagram Follower Tracker
on:
  schedule:
    - cron: '0 9 * * 1,3'  # Runs every Monday and Wednesday at 9 AM UTC
  workflow_dispatch:        # Allows manual trigger for testing

jobs:
  track-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instagrapi google-api-python-client google-auth-httplib2 google-auth-oauthlib Pillow>=8.1.1

      - name: Run tracker
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          ACCOUNTS_TO_TRACK: ${{ secrets.ACCOUNTS_TO_TRACK }}
        run: python tracker.py
